### ISSUE TITLE
خدمة ويب أو API

### ISSUE THREAD

**Issue by MagedSaeed** [MukhtarSayedSaleh/Al-Faraheedy-Project#1]
السلام عليكم ورحمة الله
تشكرون على المشروع الرائع الذي قمتم به، لدي سؤال بسيط، هل لدى المشروع أي خدمة ويب، أٌقصد API بحيث أني أرسل البيت وأستقبل تقسيمه وتشكيله وكتابته العروضية وبحره؟

شكرا جزيلا,,

**Comment by muktarsayedsaleh** [comment]
و عليكم السلام و رحمة الله و بركاته
نعم موجودة أساساً لتطبيق الهاتف المحمول، لكن تحتاج لبعض التحسينات في حال أحببت استخدامها للعموم
